on:
  push:
    branches:
      - main
    paths:
     - .github/workflows/*.yml
     - src/**/*.*
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
          access: public
      - name: Install dependencies
        run: yarn 
      - name: Build source code
        run: yarn build
      - name: Test code
        run: yarn test
      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to GPR
        run: |
         yarn publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}