name: base64-lib Continuous Delivery (CD)

on:
  workflow_call:
    secrets: 
      NPM_AUTH_TOKEN:
        required: true
      GPR_AUTH_TOKEN:
        required: true  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to GPR
        run: |
         yarn config set -s //npm.pkg.github.com/:_authToken ${{ secrets.GPR_AUTH_TOKEN }}
         yarn publish --registry https://npm.pkg.github.com --access public
        