name: base64-lib Continuous Deployment (CD)

on:
  workflow_call:
    secrets: 
      NPM_AUTH_TOKEN:
        required: true
      GPR_AUTH_TOKEN:
        required: true  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
      - name: Set auth tokens
        run: |
         npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_AUTH_TOKEN }}
         npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Check for existence of jq
        run: jq --version
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Get ready to publish to GPR
        run: |
          jq '.name = "@santi100a/base64-lib"' package.json > temp.json
          mv temp.json package.json

      - name: Publish to GPR
        run: |
         yarn publish --registry https://npm.pkg.github.com --access public